### ISSUE TITLE
Measures of concentrations of chemicals in animals

### ISSUE THREAD

**Issue by ddooley** [Southern-Cross-Plant-Science/cdno#51] opened 2021-03-25 19:14 UTC
CDNO is currently focused on 'concentration of' chemicals in 'plant structure'.  The FoodOn ontology curation team is looking at concentrations of chemicals in animal and plant materials - including mercury in fish for example. One move would be to generalize all the CDNO concentration expressions to apply to 'organism' instead of just 'plant structure'?  What are your thoughts on that?  

Assuming CDNO could take on more general organism related concentrations, we'd then be in a position to contribute them. For example, there is a variation on your mercury concentration (probably not a subclass though) which is concentration of 'methylmercury compound' in organism, which I guess is the form commonly quantified in food.

We have a [google sheet](https://docs.google.com/spreadsheets/d/1NPg1mWzhKbmCCJrCcLkbqMzWwhXy3t7rRxIMsSD0xRU) where we are working on the precomposed terms and patterns for **high** concentration of X in Y, and as well food classes having high (or low) concentrations.

Cheers,

Damion

**Comment by LilyAndres** [comment] 2021-04-01 07:57
Thanks @ddooley, we have discussed this matter with @kaiiam. I think the CDNO could be transformed into DNO for more general users easily. We could start with the nutritional components that are in CDNO at the moment and then if we have experts in nutritional components from other organisms, they can be added?

**Comment by ddooley** [comment] 2021-04-01 18:12
I'd welcome that!  I don't mind the ontology prefix change.  Would you literally go for a term ID change?  Could run that by OBO Organizing committee...

d.

**Comment by LilyAndres** [comment] 2021-04-04 13:10
We might need to discuss that with the team, but maybe we can just change the term 'plant structure' for 'organism' as you mention, maybe would be easier...

**Comment by ddooley** [comment] 2021-04-05 16:58
I support generalizing to organism.  The "concentration of ... and inheres in ... and part of some organism" axiom should be no problem.  There might be some variations for concentrations measured in body products like blood that might not anatomically be a 'part of', but that can be handled as it arises.

**Comment by kaiiam** [comment] 2021-04-06 07:44
> I think the CDNO could be transformed into DNO for more general users easily

Yes seeing as OBO doesn't seem to have a more general nutrition ontology I think CDNO should have been DNO from the start. Since we've already requested the namespace however and have the purls I'm not sure how hard/easy it would be to make that switch. I think @ramonawalls  and @ddooley would know best about this. I'm in favor of it either by switching the name or just adding more non-plant terms. 

> We might need to discuss that with the team, but maybe we can just change the term 'plant structure' for 'organism' as you mention, maybe would be easier...

We intentionally set CDNO up with a very sparse top level hierarchy 

<img width="278" alt="image" src="https://user-images.githubusercontent.com/12255688/113673619-833f1e00-96b9-11eb-9041-41b38ff8cb97.png">

to which I imagined we add a few additional top level terms analogous to what @ddooley you have in foodon. 

<img width="156" alt="image" src="https://user-images.githubusercontent.com/12255688/113674937-1167d400-96bb-11eb-8f1b-9c042885c30d.png">

But perhaps it would be better as @ddooley suggests to just have the one `organism` term replacing `plant structure`. It could be done either way but as soon as we have more entities to inhere in then crossing them with the various chemicals in concentration terms would get quite large.

It's probably not useful/informative to add the kingdom taxonomic information (plant vs animal vs fungus) to the concentration terms because in theory once someone makes use of both the CDNO concentration terms and and FOODON organismal material terms within an RDF triple store we would be able to use reasoning to differentiate the taxonomy as that's expressed in the FOODON equivalence axioms.

**Comment by CropStoreDb** [comment] 2021-04-07 17:46
@ddooley , @kaiiam - we have some comments/suggestions and will post them within 24hrs. It would be useful to set up a time for zoom call to resolve issue. Thanks

**Comment by ramonawalls** [comment] 2021-04-07 19:41
I don't think we've ever had anyone request a PURL retraction in the OBO Foundry before, as PURLS are intended not to change. I suggest you could keep CDNO (especially if you have already made a public release) and add DNO as a new ontology. CDNO can remain as an application ontology to server Graham's database and other crop-specific needs.

**Comment by ddooley** [comment] 2021-04-07 21:43
Perhaps an aikido move: make CDNO stand for Chemical Dietary Nutrition Ontology !  Or something else that begins with C!

**Comment by ramonawalls** [comment] 2021-04-07 23:26
Perfect! I had a similar thought, but could not come up with a good word
for C.

Ramona
------------------------------------------------------
Ramona L. Walls, Ph.D.
Data Scientist, Ontologies, Semantics, and Metadata, Critical Path Institute
Assistant Research Professor, Bio5 Institute, University of Arizona
Part-time artist (https://www.instagram.com/omnivoresgratitutude/)

**Comment by kaiiam** [comment] 2021-04-08 06:47
> Perhaps an aikido move: make CDNO stand for Chemical Dietary Nutrition Ontology ! Or something else that begins with C!

Complete agreement here as well.

**Comment by LilyAndres** [comment] 2021-04-09 04:01
Thanks for all the ideas, apologies for the delay in responding. We have agreed on generalising the term 'plant structure' to 'organism', i.e. substitute reference to (‘plant structure’ [PO:0009011]) with (and ‘inheres in’ ‘part of’ ‘organism’ [OBI:0100026]).

We can make these changes for the next CDNO release (soon). 
Based on your suggestion we have reviewed and discussed the wider context. We see two separate issues:

i)	Identifying the possible changes that would need to be made in order to generalize to C**** Dietary Nutrition Ontology.
ii)	The issues of working around the complexity of representing with greater subtlety pre-harvest, post-harvest and processed crop-derived food materials. 

Here we address (i):

There appears to be a decision point:
a)	Retain CDNO and establish an additional generalized DNO, or
b)	Retain CDNO but change the "Crop" to another "C" such as "Chemical".

Thoughts about "Chemical" – neat, but will limit the scope as we have outlined for CNDO, to include e.g. a ‘Physical’ attribute class for terms such as ‘energy’, that are also included in food composition databases. In addition, we anticipated (and have an outline) for a Dietary Function class, that may describe attributes that are physical in nature rather than purely chemical. So, as "food for thought", other possible "C’s" could be: "Cohesive", "Component", "Comprehensive", "Combined", "Collective"? 

In short we can see real value in making CDNO generalized.  We agree now would be the time to include additional terms representing a range of other dietary nutritional components derived from non-plant sources that are not included in CDNO at the moment - such as 'hemoglobin', 'lactoferrin', 'myoglobin', 'whey protein', etc. We’d really like to allow for establishment of related Dietary Nutrition classes, especially 'physical properties’ and ‘functional attributes’, as well as ‘dietary function’, although the latter may best be served elsewhere (although we have yet to see a meaningful outline).

For info: the initial motivation for creating CDNO is/was based on the need to annotate and compare crop-plant genetic resource databases and help make these consistent with terms used within Food Composition Tables (such as those provided by USDA and FOODON) and elsewhere. We are working on showcasing a range of simple use cases to highlight the generic nature of this by online search/filter. 
As we have previously discussed, for routine data curation, the CDNO was designed to be used with post-composed terms where these are derived from FoodOn and elsewhere (e.g. nutritional components concentration in food material that is a plant food product).

**Comment by kaiiam** [comment] 2021-04-09 07:04
I like `Comprehensive` but only if that's actually the plan for it (expanding into non plant materials) otherwise I'd say keep `Crop`. If in the future people really need a `DNO`  and it's really different in scope than CDNO then that could be done later.

**Comment by ddooley** [comment] 2021-04-09 19:43
I like `Component` because all the things CDNO measures are food components of an organism/food material/product/diet.  

One question about concentration of X in "plant structure" or organism.  Does this generalize to food materials/products generally - e.g. measuring a nutrient in baked bread or toffee.  One might have to use 'food material' instead of organism?

**Comment by CropStoreDb** [comment] 2021-04-09 22:05
I don't think _all_ attributes measured/described will be "components". For the dietary nutritional class "physical properties" one would expect terms such as energy or specific gravity, which i take to be an attribute rather than component, and are included in Food Composition Databases such as USDA, INFOODs etc as tags with no distinction from chemical components.  the class 'Functional attributes' would include terms such as 'antioxidant' which is also not a component. these classes would be non-plant specific and contribute to 'comprehensive'.

Agree re: the issue of concentration requiring a more generic definition. This is the second item that Lili referred to- I think she has a diagram or two outlining what we could suggest for discussion.

**Comment by kaiiam** [comment] 2021-04-12 07:55
I really don't think the "C" matters that much only in as far as branding. PATO for example the Phenotype And Trait Ontology is OBO's generic quality ontology with both physical qualities like `concentration` and biological traits like `ploidy`. Is the name a little confusing yes but life goes on. 

> One question about concentration of X in "plant structure" or organism. Does this generalize to food materials/products generally - e.g. measuring a nutrient in baked bread or toffee. 

We could have both if needed, i.e., concentrations of X's in `plant structure` and concentrations of X's or a different set of Y's in `organism`. 

> One might have to use 'food material' instead of organism?

Wouldn't it be better to try and use a top level term from PO or OBI or UBERON? Although perhaps not if it meant to be used in conjunction with other terms like foodon's`organismal material` terms like I asked [above](https://github.com/Southern-Cross-Plant-Science/cdno/issues/51#issuecomment-813904838).

**Comment by LilyAndres** [comment] 2021-04-13 06:11
> One question about concentration of X in "plant structure" or organism. Does this generalize to food materials/products generally - e.g. measuring a nutrient in baked bread or toffee. One might have to use 'food material' instead of organism?

I think we should discuss this in a zoom meeting @ddooley, @kaiiam? 

In the meantime, thank you all for the helpful feedback. Good point @kaiiam about the ‘C’ being label rather than deep definition. 

@CropStoreDb and I decided that **‘Compositional Dietary Nutrition Ontology’** would befit the intended scope that would also extend to animals, other life-forms and perhaps beyond. We have discussed further and looked at the scope and classes/terms defined within ONS, ONE, FOBI and think that these do not occupy the domain space that the updated CDNO would occupy, and would benefit from access to CDNO mk2. 
In the short-medium term, we would update the scope (to change `plant structure` for `organism`) and are keen to introduce well-defined classes `physical attribute` and  `dietary function`, along with a few examples.  If the `Compositional` for `Crop` substitution looks reasonable to @ramonawalls, then it would be good to know how formally to proceed.

**Comment by kaiiam** [comment] 2021-04-13 06:59
> zoom meeting

@LilyAndres to try and organize. I don't have a ton of bandwidth for this but will try to make it if it's not incredibly late in CET (spanning Australia, PST and CET can get super late in Europe).

> physical attribute

Make sure not to duplicate anything in PATO (or elsewhere) in theory we should be importing or pushing general phenotypic or characteristics there, depending on what such terms would be.

> FOBI

I'm concerned about some of their practices duplicating existing CHEBI terms within their own namespace, I really don't want to see CDNO to violate or be perceived to be violating OBO principles.  

> ONS

I wasn't aware of this the Ontology for Nutritional Studies. So it looks like there might already be an existing OBO ontology covering dietary and nutritional content? I've had a quick look at their [github repo](https://github.com/enpadasi/Ontology-for-Nutritional-Studies) although I disagree with some of their import choices, we should probably either coordinate with them or at least not overlap in content. I'm not seeing new terms in ONS (no base file) looks like from their description it's just imports of existing ontologies so perhaps this is more like an application ontology? ONE seems to be similar but is downstream of (dependent on and importing) ONS. 

@ddooley are you familiar with ONS/ONE? Any thoughts on this?

**Comment by CropStoreDb** [comment] 2021-04-13 07:25
re: physical attribute - as with 'dietary nutritional component', 'nutritional physical attribute' would be organised in a way that made sense in the context of nutritional composition and related measures. Definitely re-using terms from PATO etc, in same way that ChEBI terms were re-used in the nutritional component class.
 From our exploration (now and previously) for FOBI/ONS these seem rather incomplete and not focused on the quantification of components/attributes of raw material food materials. We would wish to do a formal check of this to ensure there is not duplication, but the domain scopes seem rather distinct from CDNO.

**Comment by ddooley** [comment] 2021-04-13 20:58
@kaiiam FOBI, ONS, and ONE are working together to coordinate domains and place their parts in a hierarchy.  FOBI has some duplicate chemical terms but tried to reuse CHEBI as much as possible - its mostly about biomarker detection in stool and urine; ONS and ONE are differentiating in that the former will be working on for example fermentation details after a soon update that will make their content look much better (loaded with new diet terms created last year in [JFOW](https://github.com/FoodOntology/joint-food-ontology-wg/)), ONE is focusing on study document parts for nutritional studies and surveys (with document part terms going into OBI).  CDNO focus on concentration datastructures helps them all.

**Comment by kaiiam** [comment] 2021-04-14 06:03
@CropStoreDb thank sounds good!

@ddooley thanks for clarifying and for the link to JFOW and that they can all work together rather than be duplicative. 

> FOBI

@ddooley at some point maybe we should checkup on the possible CHEBI term duplication issue in FOBI https://github.com/pcastellanoescuder/FoodBiomarkerOntology/issues/3

**Comment by LilyAndres** [comment] 2021-04-14 07:18
Ok if no one has any objection I think we are going for **‘Compositional Dietary Nutrition Ontology’**. The next thing and that's why I would like to have a meeting is to choose  `'organism' [OBI:0100026]`? But maybe it might not work for the `'concentration of cannabinoid in brownies'` for FoodOn @ddooley?

**Comment by kaiiam** [comment] 2021-04-28 08:32
xref https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1483#event-4652238227 which was just closed 

Here again are Nico's instructions:

> Make sure that the Markdown and (potentially) PURL configs have the correct information (i.e. make pull requests on these two files to change the names, and, potentially, the domains).

@LilyAndres can you take care of this? Let us know if you need help. 

Separate action item: from Allan R regarding changing the terms:

> The way I would handle it is that If there's been an official release with the older terms I would deprecate and create new. If it's just been in an unreleased development version then there's no need. If it has been released and you are sure that you know all users of the ontology and have confirmed that they can accept the change, then changing without deprecating would be fine, but in that case I would update the release to have the changes as well so that other's don't pick it up and have the wrong definition.

I also think @LilyAndres you should try to do this. I think we fit the last case keeping the iris's but changing the release. Regardless @LilyAndres this would be a good opportunity for you to get more hands on with the system. You can let me know if you run into problems changing the terms in our workflow, but it should all be documented in our [Intermediate-CDNO-Compile-Instructions](https://github.com/Southern-Cross-Plant-Science/cdno/wiki/Intermediate-CDNO-Compile-Instructions). I'm not sure about changing the release but that's part 2 of this assignment so we can deal with that after making the change to the terms. Make sure to do this as a PR on a branch and tag @ddooley and myself for review.

**Comment by LilyAndres** [comment] 2021-04-28 15:00
>@LilyAndres can you take care of this? Let us know if you need help.

Yes, I will do that, thanks.

>@LilyAndres this would be a good opportunity for you to get more hands on with the system

I agree, thanks @kaiiam I will let you know how it goes.

**Comment by kaiiam** [comment] 2021-05-07 08:32
@LilyAndres and I just merged https://github.com/Southern-Cross-Plant-Science/cdno/pull/52 to deal with this. We can close this later if that sorts this issue sufficiently.

**Comment by LilyAndres** [comment] 2021-06-09 02:51
The terms in concentration class have been changed from plant structure to material entity, I will close this issue now. Thanks.

**Closed by LilyAndres** 2021-06-09 02:51 UTC
